os: linux
services: docker
language: minimal
install: skip
addons:
  apt:
    packages:
      - pass

env: IMAGE="pkg"

script: ../pack.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ../travis/run.sh "$IMAGE"
    on:
      repo: ghdl/docker
      branch: pack

